# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "quickui-rails"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kristian Mandrup"]
  s.date = "2012-09-15"
  s.description = "Use Quick UI components in your Rails app!!!"
  s.email = "kmandrup@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/quickui-rails.rb",
    "spec/quickui-rails_spec.rb",
    "spec/spec_helper.rb",
    "vendor/assets/images/mobileCheckmark.png",
    "vendor/assets/images/mobileCheckmarkLarge.png",
    "vendor/assets/images/mobileDisclosureIndicator.png",
    "vendor/assets/images/mobileDisclosureIndicatorSelected.png",
    "vendor/assets/images/search_16x16.png",
    "vendor/assets/javascripts/quickui-catalog/CalendarMonthNavigator.coffee",
    "vendor/assets/javascripts/quickui-catalog/Carousel.SequenceNavigator.coffee",
    "vendor/assets/javascripts/quickui-catalog/FlickrInterestingNavigator.CalendarMonthNavigator.coffee",
    "vendor/assets/javascripts/quickui-catalog/LateralNavigator.coffee",
    "vendor/assets/javascripts/quickui-catalog/MobileLink.coffee",
    "vendor/assets/javascripts/quickui-catalog/MobileLinkList.coffee",
    "vendor/assets/javascripts/quickui-catalog/MobileListBox.coffee",
    "vendor/assets/javascripts/quickui-catalog/MonthAndYear.coffee",
    "vendor/assets/javascripts/quickui-catalog/SequenceNavigator.LateralNavigator.coffee",
    "vendor/assets/javascripts/quickui-catalog/VerticalAlign.coffee",
    "vendor/assets/javascripts/quickui/content.coffee",
    "vendor/assets/javascripts/quickui/control.coffee",
    "vendor/assets/javascripts/quickui/inDocument.coffee",
    "vendor/assets/javascripts/quickui/json.coffee",
    "vendor/assets/javascripts/quickui/layout.coffee",
    "vendor/assets/javascripts/quickui/localization.coffee",
    "vendor/assets/javascripts/quickui/properties.coffee",
    "vendor/assets/javascripts/quickui/rehydrate.coffee",
    "vendor/assets/javascripts/quickui/styles.coffee",
    "vendor/assets/javascripts/quickui/sub.coffee",
    "vendor/assets/javascripts/quickui/super.coffee",
    "vendor/assets/javascripts/quickui/utilities.coffee",
    "vendor/assets/stylesheets/quickui-catalog/CalendarMonthNavigator.less",
    "vendor/assets/stylesheets/quickui-catalog/Carousel.SequenceNavigator.less",
    "vendor/assets/stylesheets/quickui-catalog/FlickrInterestingNavigator.CalendarMonthNavigator.less",
    "vendor/assets/stylesheets/quickui-catalog/LateralNavigator.less",
    "vendor/assets/stylesheets/quickui-catalog/MobileLink.less",
    "vendor/assets/stylesheets/quickui-catalog/MobileLinkList.less",
    "vendor/assets/stylesheets/quickui-catalog/MobileListBox.less",
    "vendor/assets/stylesheets/quickui-catalog/MonthAndYear.less",
    "vendor/assets/stylesheets/quickui-catalog/SequenceNavigator.LateralNavigator.less",
    "vendor/assets/stylesheets/quickui-catalog/VerticalAlign.less",
    "vendor/assets/stylesheets/quickui-catalog/mixins.less",
    "vendor/assets/stylesheets/quickui.css"
  ]
  s.homepage = "http://github.com/kristianmandrup/quickui-rails"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Quick UI packaged for use with Rails asset pipeline"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_development_dependency(%q<jeweler>, [">= 1.8.4"])
    else
      s.add_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_dependency(%q<jeweler>, [">= 1.8.4"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 2.8.0"])
    s.add_dependency(%q<bundler>, [">= 1.0.0"])
    s.add_dependency(%q<jeweler>, [">= 1.8.4"])
  end
end

